### ISSUE TITLE
Way to move vars out of main playbook definition file?

### ISSUE THREAD

**Issue by jph** [nickhammond/ansible-logrotate#30]
Hello. Might not be the right place but worth asking:

site.yml:
```
---
- hosts: all
  become: true
  roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: logrotate for rails
          path: "/var/www/app/shared/log/*.log"
          options:
            - weekly
            - size 25M
            - missingok
            - compress
            - delaycompress
            - copytruncate
```

I want to instead do something like this:

site.yml
```
---
- hosts: all
  become: true
  roles:
    - role: nickhammond.logrotate
      include_vars:
        file: logrotate.yml
```

vars/logrotate.yml
```
logrotate_scripts:
  - name: logrotate for rails
    path: "/var/www/app/shared/log/*.log"
    options:
      - weekly
      - size 25M
      - missingok
      - compress
      - delaycompress
      - copytruncate
```

I've tried every type of include that Ansible provides. `include`, and `include_vars`. Is this just not possible? I could do it if I made my own role/task and did it within that, but that seems overkill. Thanks.
