### ISSUE TITLE
Postrotate not working

### ISSUE THREAD

**Issue by jp1987** [nickhammond/ansible-logrotate#42]
I use the following config:

```
logrotate_scripts:
  - name: node
    path: "/var/log/forever/*.log"
    options:
      - daily
      - dateext
      - missingok
      - rotate 30
      - compress
      - delaycompress
      - notifempty
      - copytruncate
    scripts:
      postrotate: "mv /var/log/forever/*.gz /var/log/forever/archive"
```

The logs are never rotated into the archive folder (running the command manually works). What am I doing wrong?
