### ISSUE TITLE
Add an option to skip logrotate installation

### ISSUE THREAD

**Issue by bobrik** [nickhammond/ansible-logrotate#5]
Some people run on weird systems without apt (like Gentoo), but still want to use configuration management tools. I can come up with PR that allows to skip logrotate installation. What do you think?

**Comment by nickhammond** [comment]
I'm not very familiar with Gentoo but it sounds like whatever other management tool you're using relies on or can use the /etc/logrotate configuration, is that correct? What would be the typical setup steps then? Sorry for the delayed reply, this didn't make it to my inbox for some reason.

**Comment by bobrik** [comment]
This one fails:

``` yaml
- name: nickhammond.logrotate | Install logrotate
  action: "{{ansible_pkg_mgr}} pkg=logrotate state=present"
```

In Gentoo `ansible_pkg_mgr` resolves to `portage`: http://docs.ansible.com/portage_module.html

Error: `msg: unsupported parameter for module: pkg`

I think we could change task to this:

``` yaml
    - name: nickhammond.logrotate | Install logrotate
      action: "{{ansible_pkg_mgr}} pkg=logrotate state=present"
      when: logrotate_install_package
```

With default value of `logrotate_install_package` set to `true`. This way it would be backwards-compatible and usable by people whose package management module does not work like apt.

What do you think?
