### ISSUE TITLE
Documentation lacking an actual playbook example

### ISSUE THREAD

**Issue by crazyguyonabike** [nickhammond/ansible-logrotate#9]
Could you provide an example of an actual playbook with this role applied, rather than just the role's required variable? An example would have saved me two days of struggling to both understand roles and how to use this particular role.

**Comment by crazyguyonabike** [comment]
For example:

``` yaml
---
 - name: deploy logrotate
   hosts: []
   become: True
   become_user: root

   roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: tomcat catalina.out
          path: "/var/log/tomcat7/catalina.out"
          options:
            - daily
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - rotate 7
```

And then do multiple instance with either 

``` yaml
---
 - name: deploy logrotate
   hosts: []
   become: True
   become_user: root

   roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: tomcat catalina.out
          path: "/var/log/tomcat7/catalina.out"
          options:
            - daily
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - rotate 7

    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: tomcat catalina.err
          path: "/var/log/tomcat7/catalina.err"
          options:
            - weekly
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - rotate 4
```

OR (suggested by bcoca on irc/freenode (#ansible)

``` yaml
---
 - name: deploy logrotate
   hosts: []
   become: True
   become_user: root

   roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: tomcat catalina.out
          path: "/var/log/tomcat7/catalina.out"
          options:
            - daily
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - rotate 7

        - name: tomcat catalina.err
          path: "/var/log/tomcat7/catalina.err"
          options:
            - weekly
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - rotate 4
```
